@startuml
class Автомобиль {
    - мощность: 150
    - стоимость: 10000.0
    - номер: "A123BC"
    - марка: "Toyota"
    - пробег: 50000
    - пройден_техосмотр: true
    + isTechInspectionPassed(): boolean
}

class Самолет {
    - мощность: 3000
    - стоимость: 300000.0
    - номер: "B456CD"
    - марка: "Boeing"
    - максимальная_высота_полёта: 10000
    + getFlightDetails(): String
}

Автомобиль : getInfo() : "Toyota, A123BC, 150л.с., 10000.0 руб., пробег 50000 км, техосмотр пройден: true"
Самолет : getFlightDetails() : "Boeing, B456CD, 3000л.с., 300000.0 руб., максимальная высота: 10000 м"
@enduml